// Copyright (c) Tailscale Inc & contributors
// SPDX-License-Identifier: BSD-3-Clause

package tailcat

import "testing"

// officialAddrFixture is a real address generated by the **official** tailcat
// v0.6.0 binary (brew), i.e. one without the Caps/Build fields. Its key is a
// throwaway key generated once for this fixture; nothing uses it.
//
// It exists to freeze two properties:
//  1. addresses without the capability fields keep parsing (and report
//     Caps == 0, which clients must read as "unknown/plain build");
//  2. re-encoding such an address is byte-for-byte identical, i.e. adding the
//     fields did not disturb the wire format for existing addresses.
const officialAddrFixture = Addr("tcpGFwWCA4A9PGgOl0d3yl0jF5eSCtEs7aHre0BFTHpA_WwQfhVWFrWCD5rLmPO9U-UgTrxPsz-02FCzZYzXJR3zCH4pByzYZSXGFxWCAuch1L0mC-EDpEX_6UcoIjsqfJ0yNKnqh8cK2GYhxedmFpGQEw")

func TestCapsRoundTrip(t *testing.T) {
	ci, err := ParseAddr(officialAddrFixture)
	if err != nil {
		t.Fatalf("ParseAddr(official fixture): %v", err)
	}
	if ci.Caps != 0 || ci.Build != "" {
		t.Errorf("official fixture advertises caps %v build %q; want none", ci.Caps, ci.Build)
	}
	if got := ci.Addr(); got != officialAddrFixture {
		t.Errorf("re-encoding an address without caps changed it:\n got %v\nwant %v", got, officialAddrFixture)
	}

	// An enhanced build's address must round-trip its advertisement, and the
	// bits must survive the parse/encode cycle clients do (Resolve, hint
	// updates) unchanged.
	ci.Caps = CapUDPForward | CapFixedPort | CapProxyForward
	ci.Build = "udp.18"
	addr := ci.Addr()
	back, err := ParseAddr(addr)
	if err != nil {
		t.Fatalf("ParseAddr(marked): %v", err)
	}
	if back.Caps != ci.Caps {
		t.Errorf("caps after round trip = %v; want %v", back.Caps, ci.Caps)
	}
	if back.Build != "udp.18" {
		t.Errorf("build after round trip = %q; want %q", back.Build, "udp.18")
	}
	if got := back.Addr(); got != addr {
		t.Errorf("re-encoding a marked address changed it:\n got %v\nwant %v", got, addr)
	}
}

func TestCapsHasAndString(t *testing.T) {
	var c Caps
	if c.Has(CapUDPForward) {
		t.Error("zero Caps advertises UDP forwarding")
	}
	if s := c.String(); s != "" {
		t.Errorf("zero Caps String() = %q; want empty", s)
	}
	c = CapUDPForward | CapFixedPort
	if !c.Has(CapUDPForward) || !c.Has(CapFixedPort) {
		t.Errorf("%v is missing bits it was built from", c)
	}
	if c.Has(CapProxyForward) {
		t.Errorf("%v claims a bit it was not given", c)
	}
	if s, want := c.String(), "udp-forward,fixed-port"; s != want {
		t.Errorf("String() = %q; want %q", s, want)
	}
	// Bit 1 is retired (was CapAgentGateway, removed 2026-09-17) and must stay
	// unassigned: addresses issued while the feature existed still carry it,
	// so reusing the bit would silently change how old addresses decode.
	if CapFixedPort != 1<<2 || CapProxyForward != 1<<3 {
		t.Errorf("retired bit 1 was reused: fixed-port=%b proxy-forward=%b", CapFixedPort, CapProxyForward)
	}
	// A legacy address with the retired bit set keeps decoding its other bits.
	legacy := Caps(1<<1) | CapFixedPort
	if legacy.String() != "fixed-port" {
		t.Errorf("legacy caps String() = %q; want %q", legacy.String(), "fixed-port")
	}
}
